Fix header resolving
Before it caused a linker error like
```
/usr/bin/ld: /tmp/cc8j1Ixp.o:(.data.rel.local+0x10): multiple definition of
`MOL_LANGUAGE_RULES'; /tmp/ccqcOtKr.o:(.data.rel.local+0x0): first
defined here
collect2: error: ld returned 1 exit status
```